Extracción de variables temporales con .dt

Segmentación lógica vectorizada con conditions / options

Validación y formateo de cadenas de texto con .str

Métricas financieras globales y agregaciones grupales estadísticas.

In [2]:
import pandas as pd
import numpy as np

df=pd.read_parquet('../data/cl_data.parquet')
df.head(10)

/home/joe/anaconda3/lib/python3.11/site-packages/pandas/core/computation/expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/home/joe/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

,id_transaccion,id_vehiculo,id_ubicacion,id_cliente,fecha,unidades,venta_bruta,marca,modelo,anio,mes,dia
0,ST-2000000,1,1,2536,2024-12-01,1,679237.0,Alfa Romeo,Giulia,2024,December,Sunday
1,ST-2000001,2,2,4867,2022-09-22,1,419582.0,Alfa Romeo,Stelvio,2022,September,Thursday
2,ST-2000002,3,1,4669,2024-12-01,1,834373.0,Alfa Romeo,Tonale,2024,December,Sunday
3,ST-2000003,4,3,899,2024-04-27,1,945477.0,Dodge,Attitude,2024,April,Saturday
4,ST-2000004,5,4,2471,2025-11-13,1,433661.0,Dodge,Durango,2025,November,Thursday
5,ST-2000005,6,4,6717,2022-01-06,1,428597.0,Dodge,Journey,2022,January,Thursday
6,ST-2000006,7,1,3359,2024-05-07,1,1065849.0,Fiat,Argo,2024,May,Tuesday
7,ST-2000007,1,4,3313,2024-06-07,1,375204.0,Alfa Romeo,Giulia,2024,June,Friday
8,ST-2000008,8,1,2377,2023-06-16,1,468735.0,Fiat,Ducato,2023,June,Friday
9,ST-2000009,4,2,1750,2022-05-16,1,802080.0,Dodge,Attitude,2022,May,Monday

In [3]:
conditions = [df['unidades']==1,(df['unidades']>1)&(df['unidades']<=4),df['unidades']>4]
options = ['individual','medio','alto']
print(type(conditions))
print(type(options))

<class 'list'>
<class 'list'>

In [4]:
df['cat_unidades'] = np.select(conditions, options, default='No aplica')
df.head(10)

,id_transaccion,id_vehiculo,id_ubicacion,id_cliente,fecha,unidades,venta_bruta,marca,modelo,anio,mes,dia,cat_unidades
0,ST-2000000,1,1,2536,2024-12-01,1,679237.0,Alfa Romeo,Giulia,2024,December,Sunday,individual
1,ST-2000001,2,2,4867,2022-09-22,1,419582.0,Alfa Romeo,Stelvio,2022,September,Thursday,individual
2,ST-2000002,3,1,4669,2024-12-01,1,834373.0,Alfa Romeo,Tonale,2024,December,Sunday,individual
3,ST-2000003,4,3,899,2024-04-27,1,945477.0,Dodge,Attitude,2024,April,Saturday,individual
4,ST-2000004,5,4,2471,2025-11-13,1,433661.0,Dodge,Durango,2025,November,Thursday,individual
5,ST-2000005,6,4,6717,2022-01-06,1,428597.0,Dodge,Journey,2022,January,Thursday,individual
6,ST-2000006,7,1,3359,2024-05-07,1,1065849.0,Fiat,Argo,2024,May,Tuesday,individual
7,ST-2000007,1,4,3313,2024-06-07,1,375204.0,Alfa Romeo,Giulia,2024,June,Friday,individual
8,ST-2000008,8,1,2377,2023-06-16,1,468735.0,Fiat,Ducato,2023,June,Friday,individual
9,ST-2000009,4,2,1750,2022-05-16,1,802080.0,Dodge,Attitude,2022,May,Monday,individual

In [5]:
df.iloc[df['unidades']==1]

,id_transaccion,id_vehiculo,id_ubicacion,id_cliente,fecha,unidades,venta_bruta,marca,modelo,anio,mes,dia,cat_unidades
0,ST-2000000,1,1,2536,2024-12-01,1,679237.0,Alfa Romeo,Giulia,2024,December,Sunday,individual
1,ST-2000001,2,2,4867,2022-09-22,1,419582.0,Alfa Romeo,Stelvio,2022,September,Thursday,individual
2,ST-2000002,3,1,4669,2024-12-01,1,834373.0,Alfa Romeo,Tonale,2024,December,Sunday,individual
3,ST-2000003,4,3,899,2024-04-27,1,945477.0,Dodge,Attitude,2024,April,Saturday,individual
4,ST-2000004,5,4,2471,2025-11-13,1,433661.0,Dodge,Durango,2025,November,Thursday,individual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
480875,ST-2536316,13,2,627,2022-11-02,1,810925.0,Jeep,Grand Cherokee,2022,November,Wednesday,individual
480876,ST-2536317,3,5,10602,2023-06-13,1,840915.0,Alfa Romeo,Tonale,2023,June,Tuesday,individual
480877,ST-2536318,5,4,10262,2024-11-13,1,511234.0,Dodge,Durango,2024,November,Wednesday,individual
480878,ST-2536319,4,4,13095,2022-02-02,1,605180.0,Dodge,Attitude,2022,February,Wednesday,individual
480879,ST-2536320,20,5,2739,2023-06-26,1,644996.0,RAM,1500,2023,June,Monday,individual

In [6]:
df['cat_unidades'].value_counts()

cat_unidades
individual    471194
medio           7285
alto            2401
Name: count, dtype: int64

In [7]:
df['id_transaccion'].str.startswith('ST-').all()

True

In [8]:
total_ventas_brutas = df['venta_bruta'].sum() 
total_unidades_vendidas = df['unidades'].sum()
ticket_promedio = total_ventas_brutas / total_unidades_vendidas

print(f'El total de ventas brutas es: ${total_ventas_brutas:,.1f} pesos')
print(f'El total de unidades vendidas es: {total_unidades_vendidas:,} unidades')
print(f'El ticket promedio es: ${ticket_promedio:,.2f} pesos')

El total de ventas brutas es: $325,803,767,465.0 pesos
El total de unidades vendidas es: 497,769 unidades
El ticket promedio es: $654,528.04 pesos

In [9]:
top_ventas = df.groupby('id_cliente')['venta_bruta'].sum().sort_values(ascending=False).reset_index().head(10)
print(type(top_ventas))
top_ventas['venta_bruta'] = top_ventas['venta_bruta'].map('${:,.2f} MXN'.format)
top_ventas

<class 'pandas.DataFrame'>

   id_cliente         venta_bruta
0       13578  $41,707,499.00 MXN
1        8745  $41,482,775.00 MXN
2        1211  $38,703,595.00 MXN
3        4982  $38,084,908.00 MXN
4       14361  $37,808,617.00 MXN
5        5715  $37,659,448.00 MXN
6       15073  $37,350,084.00 MXN
7        4732  $37,102,409.00 MXN
8        3793  $37,046,973.00 MXN
9         937  $36,742,002.00 MXN

In [10]:
des_ubicacion = df.groupby('id_ubicacion')['venta_bruta'].agg(desviacion_std_ventas='std',mediana_de_ventas='median',promedio_venta='mean').round().reset_index()
print(type(des_ubicacion['promedio_venta']))
des_ubicacion['coef_variacion_%'] = ((des_ubicacion['desviacion_std_ventas'] / des_ubicacion['promedio_venta']) * 100).round()
des_ubicacion

<class 'pandas.Series'>

,id_ubicacion,desviacion_std_ventas,mediana_de_ventas,promedio_venta,coef_variacion_%
0,1,293349.0,655889.0,678454.0,43.0
1,2,291663.0,654438.0,678089.0,43.0
2,3,278739.0,652026.0,673832.0,41.0
3,4,291136.0,655475.0,677611.0,43.0
4,5,289420.0,657531.0,677574.0,43.0
5,6,297252.0,653510.0,677833.0,44.0
6,7,285256.0,650920.0,673685.0,42.0

Exercise number 10

In [11]:
df.head(10)

,id_transaccion,id_vehiculo,id_ubicacion,id_cliente,fecha,unidades,venta_bruta,marca,modelo,anio,mes,dia,cat_unidades
0,ST-2000000,1,1,2536,2024-12-01,1,679237.0,Alfa Romeo,Giulia,2024,December,Sunday,individual
1,ST-2000001,2,2,4867,2022-09-22,1,419582.0,Alfa Romeo,Stelvio,2022,September,Thursday,individual
2,ST-2000002,3,1,4669,2024-12-01,1,834373.0,Alfa Romeo,Tonale,2024,December,Sunday,individual
3,ST-2000003,4,3,899,2024-04-27,1,945477.0,Dodge,Attitude,2024,April,Saturday,individual
4,ST-2000004,5,4,2471,2025-11-13,1,433661.0,Dodge,Durango,2025,November,Thursday,individual
5,ST-2000005,6,4,6717,2022-01-06,1,428597.0,Dodge,Journey,2022,January,Thursday,individual
6,ST-2000006,7,1,3359,2024-05-07,1,1065849.0,Fiat,Argo,2024,May,Tuesday,individual
7,ST-2000007,1,4,3313,2024-06-07,1,375204.0,Alfa Romeo,Giulia,2024,June,Friday,individual
8,ST-2000008,8,1,2377,2023-06-16,1,468735.0,Fiat,Ducato,2023,June,Friday,individual
9,ST-2000009,4,2,1750,2022-05-16,1,802080.0,Dodge,Attitude,2022,May,Monday,individual

Giving order to month column

In [12]:
month_order = ['January','February','March', 'April','May','June', 'July', 'August','September','October','November','December' ]
df['mes'] = pd.Categorical(df['mes'], categories=month_order, ordered=True)

Calculating month over Month values

In [13]:
tendencia_MoM = df.groupby(['anio','mes'])['venta_bruta'].sum().reset_index()
tendencia_MoM['MoM'] = (tendencia_MoM['venta_bruta'].pct_change())*100
#tendencia_MoM.head(10)
#print(type(tendencia_MoM))

Day order

In [14]:
day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday','Friday','Saturday','Sunday']
df['dia'] = pd.Categorical(df['dia'], categories=day_order, ordered=True)

In [15]:
tendencia_dia = df.groupby(['dia'])['venta_bruta'].sum().reset_index().sort_values('venta_bruta', ascending=False)
tendencia_dia.head(10)

         dia   venta_bruta
2  Wednesday  4.664851e+10
5   Saturday  4.663290e+10
6     Sunday  4.662500e+10
0     Monday  4.659279e+10
3   Thursday  4.658536e+10
1    Tuesday  4.639654e+10
4     Friday  4.632268e+10

In [16]:
def outliers_IQR(df, serie):
    Q1 = df[serie].quantile(0.25)
    Q3 = df[serie].quantile(0.75) 
    IQR = Q3-Q1

    limite_inf = Q1 - (1.5 * IQR)
    limite_sup = Q3 + (1.5 * IQR)

    outliers = df[(df[serie] < limite_inf) | (df[serie] > limite_sup)]

    print(f'---Analisis IQR para {serie}---')
    print(f' El rango Q1 es {Q1}')
    print(f' El rango Q3 es {Q3}')
    print(f' El IQR es {IQR}')
    print(f' El limite inferior es {limite_inf}')
    print(f' El limite superior es {limite_sup}')
    print(f' Total Outliers detectados: {len(outliers)} ({len(outliers)/len(df):.2%})\n')

    return outliers

In [17]:
df_outliers = outliers_IQR(df,'venta_bruta')
#df_outliers.head(10)

---Analisis IQR para venta_bruta---
 El rango Q1 es 497845.5
 El rango Q3 es 812181.5
 El IQR es 314336.0
 El limite inferior es 26341.5
 El limite superior es 1283685.5
 Total Outliers detectados: 9761 (2.03%)

In [18]:
conteo_uniques = df['id_vehiculo'].unique()
conteo_uniques

<IntegerArray>
[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
 20, 21, 22, 23]
Length: 23, dtype: Int64

In [19]:
df_char = pd.read_csv('../data/char_vehiculos.csv')
df_char.info()

<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_vehiculo  23 non-null     int64
 1   marca        23 non-null     str
 2   modelo       23 non-null     str
 3   plataforma   23 non-null     str
dtypes: int64(1), str(3)
memory usage: 1.2 KB

In [20]:
catalogo = df.merge(df_char[['id_vehiculo','plataforma']], on='id_vehiculo', how='left')

print(len(catalogo))
print(len(df))

catalogo.head(10)

480880
480880

,id_transaccion,id_vehiculo,id_ubicacion,id_cliente,fecha,unidades,venta_bruta,marca,modelo,anio,mes,dia,cat_unidades,plataforma
0,ST-2000000,1,1,2536,2024-12-01,1,679237.0,Alfa Romeo,Giulia,2024,December,Sunday,individual,Lujo
1,ST-2000001,2,2,4867,2022-09-22,1,419582.0,Alfa Romeo,Stelvio,2022,September,Thursday,individual,Lujo
2,ST-2000002,3,1,4669,2024-12-01,1,834373.0,Alfa Romeo,Tonale,2024,December,Sunday,individual,SUV
3,ST-2000003,4,3,899,2024-04-27,1,945477.0,Dodge,Attitude,2024,April,Saturday,individual,Familiar
4,ST-2000004,5,4,2471,2025-11-13,1,433661.0,Dodge,Durango,2025,November,Thursday,individual,Lujo
5,ST-2000005,6,4,6717,2022-01-06,1,428597.0,Dodge,Journey,2022,January,Thursday,individual,SUV
6,ST-2000006,7,1,3359,2024-05-07,1,1065849.0,Fiat,Argo,2024,May,Tuesday,individual,Familiar
7,ST-2000007,1,4,3313,2024-06-07,1,375204.0,Alfa Romeo,Giulia,2024,June,Friday,individual,Lujo
8,ST-2000008,8,1,2377,2023-06-16,1,468735.0,Fiat,Ducato,2023,June,Friday,individual,Carga
9,ST-2000009,4,2,1750,2022-05-16,1,802080.0,Dodge,Attitude,2022,May,Monday,individual,Familiar

In [21]:
df['periodo'] = df['fecha'].dt.to_period('M')
rec_clientes = df.groupby('id_cliente')['periodo'].unique().reset_index()
rec_clientes['meses_activo'] = rec_clientes['periodo'].apply(len)
clientes_recurrentes = rec_clientes[rec_clientes['meses_activo'] >= 3 ]
#print(type(clientes_recurrentes))
clientes_recurrentes.head(10)

   id_cliente                                            periodo  meses_activo
0           1  [2022-11, 2023-12, 2025-01, 2022-08, 2023-08, ...            28
1           2  [2023-11, 2024-07, 2022-06, 2025-11, 2022-12, ...            19
2           3  [2024-10, 2024-12, 2023-09, 2025-01, 2023-06, ...            27
3           4  [2022-09, 2024-01, 2025-12, 2024-04, 2025-11, ...            25
4           5  [2022-11, 2024-01, 2025-05, 2023-10, 2024-10, ...            20
5           6  [2025-06, 2024-05, 2024-12, 2022-11, 2024-11, ...            19
6           7  [2025-11, 2024-01, 2023-11, 2024-08, 2022-12, ...            18
7           8  [2023-10, 2023-11, 2024-09, 2023-12, 2023-07, ...            23
8           9  [2024-11, 2024-09, 2023-08, 2022-11, 2022-06, ...            23
9          10  [2025-02, 2023-06, 2024-11, 2023-07, 2023-10, ...            17

In [46]:
total_ventas_brutas = df['venta_bruta'].sum()
ochenta_prc =total_ventas_brutas * 0.8
#print(total_ventas_brutas)
#print(ochenta_prc)
df_pareto_1 = df.groupby('id_cliente')['venta_bruta'].sum().reset_index()
df_pareto_1 = df_pareto_1.sort_values('venta_bruta', ascending=False)
df_pareto_1['suma_ac'] = df_pareto_1['venta_bruta'].cumsum()
df_pareto_1['prc_ac'] = (df_pareto_1['suma_ac'] / total_ventas_brutas) * 100
#print(f"total : {df_pareto_1['prc_ac'].iloc[-1]}")
df_pareto_1.head(10)

       id_cliente  venta_bruta      suma_ac    prc_ac
13577       13578   41707499.0   41707499.0  0.012801
8744         8745   41482775.0   83190274.0  0.025534
1210         1211   38703595.0  121893869.0  0.037413
4981         4982   38084908.0  159978777.0  0.049103
14360       14361   37808617.0  197787394.0  0.060708
5714         5715   37659448.0  235446842.0  0.072266
15072       15073   37350084.0  272796926.0  0.083730
4731         4732   37102409.0  309899335.0  0.095118
3792         3793   37046973.0  346946308.0  0.106489
936           937   36742002.0  383688310.0  0.117767

In [65]:
df_pareto_2 = df_pareto_1[df_pareto_1['prc_ac'] <= 80]
df_pareto_2.tail(10)
#print(len(df_pareto_2))

       id_cliente  venta_bruta       suma_ac     prc_ac
924           925   18385527.0  2.604605e+11  79.943994
14469       14470   18385316.0  2.604789e+11  79.949637
4178         4179   18384739.0  2.604973e+11  79.955280
14507       14508   18382848.0  2.605157e+11  79.960923
11387       11388   18382716.0  2.605341e+11  79.966565
13492       13493   18380175.0  2.605525e+11  79.972206
11234       11235   18379964.0  2.605708e+11  79.977848
5725         5726   18379304.0  2.605892e+11  79.983489
6733         6734   18378690.0  2.606076e+11  79.989130
9080         9081   18378586.0  2.606260e+11  79.994771

In [69]:
porcentaje = (len(df_pareto_2) / len(df_pareto_1)) * 100
print(f'Clientes analizados : {len(df_pareto_1)}')
print(f'Clientes con los que se alcanza el 80% : {len(df_pareto_2)}')
print(f'Porcentaje de clientes : {porcentaje:,.2f} %')

Clientes analizados : 15432
Clientes con los que se alcanza el 80% : 11395
Porcentaje de clientes : 73.84 %