Extracción de variables temporales con .dt

Segmentación lógica vectorizada con conditions / options

Validación y formateo de cadenas de texto con .str

Métricas financieras globales y agregaciones grupales estadísticas.

In [1]:
import pandas as pd
import numpy as np

df=pd.read_parquet('../data/cl_data.parquet')
df.head(10)

/home/joe/anaconda3/lib/python3.11/site-packages/pandas/core/computation/expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/home/joe/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

,id_transaccion,id_vehiculo,id_ubicacion,id_cliente,fecha,unidades,venta_bruta,marca,modelo,anio,mes,dia
0,ST-2000000,1,1,2536,2024-12-01,1,679237.0,Alfa Romeo,Giulia,2024,December,Sunday
1,ST-2000001,2,2,4867,2022-09-22,1,419582.0,Alfa Romeo,Stelvio,2022,September,Thursday
2,ST-2000002,3,1,4669,2024-12-01,1,834373.0,Alfa Romeo,Tonale,2024,December,Sunday
3,ST-2000003,4,3,899,2024-04-27,1,945477.0,Dodge,Attitude,2024,April,Saturday
4,ST-2000004,5,4,2471,2025-11-13,1,433661.0,Dodge,Durango,2025,November,Thursday
5,ST-2000005,6,4,6717,2022-01-06,1,428597.0,Dodge,Journey,2022,January,Thursday
6,ST-2000006,7,1,3359,2024-05-07,1,1065849.0,Fiat,Argo,2024,May,Tuesday
7,ST-2000007,1,4,3313,2024-06-07,1,375204.0,Alfa Romeo,Giulia,2024,June,Friday
8,ST-2000008,8,1,2377,2023-06-16,1,468735.0,Fiat,Ducato,2023,June,Friday
9,ST-2000009,4,2,1750,2022-05-16,1,802080.0,Dodge,Attitude,2022,May,Monday

In [2]:
conditions = [df['unidades']==1,(df['unidades']>1)&(df['unidades']<=4),df['unidades']>4]
options = ['individual','medio','alto']
print(type(conditions))
print(type(options))

<class 'list'>
<class 'list'>

In [3]:
df['cat_unidades'] = np.select(conditions, options, default='No aplica')
df.head(10)

,id_transaccion,id_vehiculo,id_ubicacion,id_cliente,fecha,unidades,venta_bruta,marca,modelo,anio,mes,dia,cat_unidades
0,ST-2000000,1,1,2536,2024-12-01,1,679237.0,Alfa Romeo,Giulia,2024,December,Sunday,individual
1,ST-2000001,2,2,4867,2022-09-22,1,419582.0,Alfa Romeo,Stelvio,2022,September,Thursday,individual
2,ST-2000002,3,1,4669,2024-12-01,1,834373.0,Alfa Romeo,Tonale,2024,December,Sunday,individual
3,ST-2000003,4,3,899,2024-04-27,1,945477.0,Dodge,Attitude,2024,April,Saturday,individual
4,ST-2000004,5,4,2471,2025-11-13,1,433661.0,Dodge,Durango,2025,November,Thursday,individual
5,ST-2000005,6,4,6717,2022-01-06,1,428597.0,Dodge,Journey,2022,January,Thursday,individual
6,ST-2000006,7,1,3359,2024-05-07,1,1065849.0,Fiat,Argo,2024,May,Tuesday,individual
7,ST-2000007,1,4,3313,2024-06-07,1,375204.0,Alfa Romeo,Giulia,2024,June,Friday,individual
8,ST-2000008,8,1,2377,2023-06-16,1,468735.0,Fiat,Ducato,2023,June,Friday,individual
9,ST-2000009,4,2,1750,2022-05-16,1,802080.0,Dodge,Attitude,2022,May,Monday,individual

In [4]:
df.iloc[df['unidades']==1]

,id_transaccion,id_vehiculo,id_ubicacion,id_cliente,fecha,unidades,venta_bruta,marca,modelo,anio,mes,dia,cat_unidades
0,ST-2000000,1,1,2536,2024-12-01,1,679237.0,Alfa Romeo,Giulia,2024,December,Sunday,individual
1,ST-2000001,2,2,4867,2022-09-22,1,419582.0,Alfa Romeo,Stelvio,2022,September,Thursday,individual
2,ST-2000002,3,1,4669,2024-12-01,1,834373.0,Alfa Romeo,Tonale,2024,December,Sunday,individual
3,ST-2000003,4,3,899,2024-04-27,1,945477.0,Dodge,Attitude,2024,April,Saturday,individual
4,ST-2000004,5,4,2471,2025-11-13,1,433661.0,Dodge,Durango,2025,November,Thursday,individual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
480875,ST-2536316,13,2,627,2022-11-02,1,810925.0,Jeep,Grand Cherokee,2022,November,Wednesday,individual
480876,ST-2536317,3,5,10602,2023-06-13,1,840915.0,Alfa Romeo,Tonale,2023,June,Tuesday,individual
480877,ST-2536318,5,4,10262,2024-11-13,1,511234.0,Dodge,Durango,2024,November,Wednesday,individual
480878,ST-2536319,4,4,13095,2022-02-02,1,605180.0,Dodge,Attitude,2022,February,Wednesday,individual
480879,ST-2536320,20,5,2739,2023-06-26,1,644996.0,RAM,1500,2023,June,Monday,individual

In [5]:
df['cat_unidades'].value_counts()

cat_unidades
individual    471194
medio           7285
alto            2401
Name: count, dtype: int64

In [6]:
df['id_transaccion'].str.startswith('ST-').all()

True

In [7]:
total_ventas_brutas = df['venta_bruta'].sum() 
total_unidades_vendidas = df['unidades'].sum()
ticket_promedio = total_ventas_brutas / total_unidades_vendidas

print(f'El total de ventas brutas es: ${total_ventas_brutas:,.1f} pesos')
print(f'El total de unidades vendidas es: {total_unidades_vendidas:,} unidades')
print(f'El ticket promedio es: ${ticket_promedio:,.2f} pesos')

El total de ventas brutas es: $325,803,767,465.0 pesos
El total de unidades vendidas es: 497,769 unidades
El ticket promedio es: $654,528.04 pesos

In [8]:
top_ventas = df.groupby('id_cliente')['venta_bruta'].sum().sort_values(ascending=False).reset_index().head(10)
print(type(top_ventas))
top_ventas['venta_bruta'] = top_ventas['venta_bruta'].map('${:,.2f} MXN'.format)
top_ventas

<class 'pandas.DataFrame'>

   id_cliente         venta_bruta
0       13578  $41,707,499.00 MXN
1        8745  $41,482,775.00 MXN
2        1211  $38,703,595.00 MXN
3        4982  $38,084,908.00 MXN
4       14361  $37,808,617.00 MXN
5        5715  $37,659,448.00 MXN
6       15073  $37,350,084.00 MXN
7        4732  $37,102,409.00 MXN
8        3793  $37,046,973.00 MXN
9         937  $36,742,002.00 MXN

In [9]:
des_ubicacion = df.groupby('id_ubicacion')['venta_bruta'].agg(desviacion_std_ventas='std',mediana_de_ventas='median',promedio_venta='mean').round().reset_index()
print(type(des_ubicacion['promedio_venta']))
des_ubicacion['coef_variacion_%'] = ((des_ubicacion['desviacion_std_ventas'] / des_ubicacion['promedio_venta']) * 100).round()
des_ubicacion

<class 'pandas.Series'>

,id_ubicacion,desviacion_std_ventas,mediana_de_ventas,promedio_venta,coef_variacion_%
0,1,293349.0,655889.0,678454.0,43.0
1,2,291663.0,654438.0,678089.0,43.0
2,3,278739.0,652026.0,673832.0,41.0
3,4,291136.0,655475.0,677611.0,43.0
4,5,289420.0,657531.0,677574.0,43.0
5,6,297252.0,653510.0,677833.0,44.0
6,7,285256.0,650920.0,673685.0,42.0

Exercise number 10

In [ ]:
tendencia_MoM =